name: Farmer
author: Geik, Amowny, WaterArchery, hyperion, rudde, mehmet-27, Khontrom, weesli
main: xyz.geik.farmer.Main
version: v6-b109
api-version: 1.13
softdepend: [PlaceholderAPI, Vault, RoyaleEconomy, PlayerPoints, GrinGotts, ElementalGems, ASkyBlock, BentoBox, SuperiorSkyblock2, GriefPrevention, FabledSkyBlock, Lands, IridiumSkyblock, UltimateClaims]
loadbefore: [AutoPickup]
folia-supported: true
commands:
  farmer:
    description: Main command of farmer
    aliases: [farm, çiftçi, fm, ciftci]